/robot_news_r2d2:
  ros__parameters:
    name: "R2D2"

/robot_news_c3po:
  ros__parameters:
    name: "C3PO"

/robot_news_bb8:
  ros__parameters:
    name: "BB8"

/robot_news_giskard:
  ros__parameters:
    name: "GISKARD"

/robot_news_daneel:
  ros__parameters:
    name: "DANEEL"
